name: "Heroku Review Apps Action"
description: Use Heroku Review Apps API to create review apps
author: Andrea Bernicchia
inputs:
  heroku-api-key:
    description: "Your Heroku API key"
    required: true
  heroku-pipeline-id:
    description: "The Heroku pipeline ID to create Review Apps"
    required: true
  remove-git-folder:
    description: "When true the .git/ folder is removed before creating the tar"
    required: false
    default: true

branding:
  icon: "play-circle"
  color: "purple"

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        echo "Validating inputs ..."
        [[ "${{ inputs.heroku-api-key }}" ]] || { echo "heroku-api-key is required" ; exit 1; }
        [[ "${{ inputs.heroku-pipeline-id }}" ]] || { echo "heroku-pipeline-id is required" ; exit 1; }
        [[ "${{ inputs.remove-git-folder }}" != "true" && "${{ inputs.remove-git-folder }}" != "false" ]] && { echo "invalid value for remove-git-folder input. Expected 'true' or 'false'" ; exit 1; }
        echo "All inputs are valid"

    # this action must be preceeded by the actions/checkout to retrieve the source code
    # files filtering must happen at checkout (see sparse-checkout from https://github.com/actions/checkout), 
    # here everything is included using find to avoid tar unwanted options injection in case the source repo has been compromised (with files name that mimic tar options e.g. "--checkpoint-action=exec=sh shell.sh")
    # tar output file is created under /tmp to avoid the "warning file changed as we read it" that forces exit code to 1
    # .git folder is removed before creating the tar if remove-git-folder is true - .git folder is the only dir that cannot be filtered by checkout
    - name: Compress Source Code
      if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
      shell: bash
      run: |
        echo "Removing .git ..."
        [[ "${{ inputs.remove-git-folder }}" == "true" ]] && { echo "Removing .git folder ..." ; rm -rf .git }
        echo "Compressing Source Code ..."
        find . -name "*" -print0 | xargs -0 tar -czvf /tmp/source.tar.gz

    - name: Create Source Endpoint
      if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
      shell: bash
      run: |
        echo "Creating a source endpoint ..."
        SOURCE_ENDPOINT=$(curl --fail-with-body -X POST https://api.heroku.com/sources \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.heroku+json; version=3" \
        -H "Authorization: Bearer ${{ inputs.heroku-api-key }}" | \
        jq -er '{get: .source_blob.get_url, put: .source_blob.put_url}')
        echo SOURCE_ENDPOINT=$SOURCE_ENDPOINT >> $GITHUB_ENV

    - name: Upload Source Code
      if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
      shell: bash
      run: |
        URL=$(echo ${{ toJSON(env.SOURCE_ENDPOINT) }} | jq -er '.put')
        curl --fail-with-body $URL -X PUT -H 'Content-Type:' --data-binary @/tmp/source.tar.gz

    - name: Create Review App
      if: ${{ github.event_name == 'pull_request' && (github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.action == 'reopened') }}
      shell: bash
      run: |
        echo "Create Review App"
        SOURCE_GET_URL=$(echo ${{ toJSON(env.SOURCE_ENDPOINT) }} | jq -er '.get')        
        curl --fail-with-body -X POST https://api.heroku.com/review-apps \
        -d '{"source_blob":{"url":"'"$SOURCE_GET_URL"'", "version": "'"${GITHUB_SHA::7}"'"},
        "pipeline":"'"${{ inputs.heroku-pipeline-id }}"'",
        "pr_number":${{ github.event.pull_request.number }},
        "branch":"'"${{ github.event.pull_request.head.ref }}"'"        
        }' \
        -H "Accept: application/vnd.heroku+json; version=3" \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ inputs.heroku-api-key }}"

    - name: Delete Review App
      if: ${{ github.event_name == 'pull_request' && github.event.action == 'closed' }}
      shell: bash
      run: |
        REVIEWAPP_ID_TOBEDELETED=$(curl --fail-with-body "https://api.heroku.com/pipelines/${{ inputs.heroku-pipeline-id }}/review-apps" \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.heroku+json; version=3" \
        -H "Authorization: Bearer ${{ inputs.heroku-api-key }}" | \
        jq -er 'map(select((.pr_number == ${{ github.event.pull_request.number }}) and (.branch == "${{ github.event.pull_request.head.ref }}")) | .id) | .[]')

        echo "Deleting Review App $REVIEWAPP_ID_TOBEDELETED ..."
        curl --fail-with-body -X DELETE "https://api.heroku.com/review-apps/$REVIEWAPP_ID_TOBEDELETED" \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.heroku+json; version=3" \
        -H "Authorization: Bearer ${{ inputs.heroku-api-key }}"